# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_GAME_OPT)    += game_opt/
obj-$(CONFIG_OPLUS_FEATURE_GEAS)        += geas/
obj-$(CONFIG_OPLUS_FEATURE_SCHED_EXT)   += sched_ext/
